# Generated by Django 6.0 on 2026-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
