# Generated by Django 6.0 on 2026-01-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='e-commerce', max_length=100)),
                ('hero_subtitle', models.TextField()),
                ('mission_statement', models.TextField()),
                ('story_description', models.TextField()),
                ('story_image', models.ImageField(upload_to='about/')),
                ('value_one_title', models.CharField(max_length=100)),
                ('value_one_desc', models.TextField()),
                ('value_two_title', models.CharField(max_length=100)),
                ('value_two_desc', models.TextField()),
            ],
        ),
    ]
