# Generated by Django 6.0 on 2026-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='value_three_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='value_three_title',
            field=models.CharField(default='Community', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.CharField(help_text='Short catchy line under the title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_statement',
            field=models.TextField(help_text="Your brand's 'Why'."),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='store_name',
            field=models.CharField(default='Animataed', help_text='This will be the floating animated text.', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_description',
            field=models.TextField(help_text='The full history of your store.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='value_one_title',
            field=models.CharField(default='Quality', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='value_two_title',
            field=models.CharField(default='Innovation', max_length=100),
        ),
    ]
