# Generated by Django 6.0 on 2026-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_aboutpage_value_three_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms & Conditions', max_length=200)),
                ('last_updated', models.DateField(auto_now=True)),
                ('introduction', models.TextField()),
                ('use_of_website', models.TextField()),
                ('user_accounts', models.TextField()),
                ('product_info', models.TextField()),
                ('liability', models.TextField()),
                ('changes_to_terms', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
    ]
