# Generated by Django 6.0 on 2026-02-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_termsandconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
