# Generated by Django 6.0 on 2026-02-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
    ]
