# Generated by Django 6.0 on 2026-01-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='rom',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
