# Generated by Django 6.0 on 2026-01-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_size_product_rename_image_productimage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(max_length=50),
        ),
    ]
