# Generated by Django 6.0 on 2026-02-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
