# Generated by Django 6.0 on 2026-02-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminsubcategory', to='product.category')),
            ],
        ),
    ]
