# Generated by Django 6.0 on 2026-02-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_adminsubcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSubCategory',
        ),
    ]
