# Generated by Django 6.0 on 2026-01-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_banner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Banner Title', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
