# Generated by Django 6.0 on 2026-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_adminsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
