# Generated by Django 6.0 on 2026-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_memory_alter_product_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
