# Generated by Django 6.0 on 2026-01-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_at',
        ),
    ]
