# Generated by Django 6.0 on 2026-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_wishlist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prise',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
