# Generated by Django 6.0 on 2026-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
