# Generated by Django 6.0 on 2026-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_coupon_min_amount_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.IntegerField(),
        ),
    ]
