# Generated by Django 6.0 on 2026-02-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_price_order_total_price_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
