# Generated by Django 6.0 on 2026-02-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderitem_status_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
    ]
