# Generated by Django 6.0 on 2026-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
