# Generated by Django 6.0 on 2026-02-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_created_at_orderitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reordered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorders', to='order.order'),
        ),
    ]
