# Generated by Django 6.0 on 2026-02-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_feedback'),
        ('product', '0012_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
